version: "3"
services:
  node_app:
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
