name: Deploy Production

on:
  push:
    branches:
    - prod_branch

jobs:
  prod-deploy:
    runs-on: ubuntu-latest

    steps:
    
   
    - name: Checkout
      uses: actions/checkout@v3

    - name: Production
      run: |
        echo "Production"

   