name: Deploy Trial

on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  prod-deploy:
    runs-on: self-hosted

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Trial
      run: |
        echo "Trial"
        sleep 3600

   
